import type { Preset } from "./types";

export const PRESETS: Preset[] = [
  {
    id: "minimal-white",
    name: "Minimal White",
    animation: "word-reveal",
    fontFamily: '"Bricolage Grotesque", Inter, sans-serif',
    fontSize: 110,
    fontWeight: 700,
    color: "#ffffff",
    highlightColor: "#ffffff",
    shadow: "0 4px 30px rgba(0,0,0,0.55)",
    textTransform: "none",
    letterSpacing: -2,
    lineHeight: 1.05,
    backgroundDim: 0.35,
    position: "center",
  },
  {
    id: "typewriter-cinema",
    name: "Typewriter Cinema",
    animation: "typewriter",
    fontFamily: '"JetBrains Mono", ui-monospace, monospace',
    fontSize: 78,
    fontWeight: 500,
    color: "#f5f5f4",
    highlightColor: "#ffd5d5",
    shadow: "0 2px 16px rgba(0,0,0,0.7)",
    textTransform: "none",
    letterSpacing: 0,
    lineHeight: 1.2,
    backgroundDim: 0.5,
    position: "bottom",
  },
  {
    id: "bollywood-neon",
    name: "Bollywood Neon",
    animation: "fade-in",
    fontFamily: '"Bricolage Grotesque", Inter, sans-serif',
    fontSize: 130,
    fontWeight: 700,
    color: "#ffe680",
    highlightColor: "#ff5d5d",
    shadow: "0 0 24px rgba(255,93,93,0.55), 0 0 60px rgba(255,230,128,0.35)",
    textTransform: "uppercase",
    letterSpacing: -1,
    lineHeight: 1,
    backgroundDim: 0.3,
    position: "center",
  },
  {
    id: "karaoke-pop",
    name: "Karaoke Pop",
    animation: "karaoke",
    fontFamily: '"Inter", system-ui, sans-serif',
    fontSize: 96,
    fontWeight: 700,
    color: "#9ba1ac",
    highlightColor: "#ffffff",
    shadow: "0 6px 24px rgba(0,0,0,0.5)",
    textTransform: "none",
    letterSpacing: -1,
    lineHeight: 1.15,
    backgroundDim: 0.45,
    position: "bottom",
  },
];

export function presetById(id: string): Preset {
  return PRESETS.find((p) => p.id === id) ?? PRESETS[0];
}
